# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-13 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.CharField(max_length=200),
        ),
    ]
