# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-13 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20181013_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
