# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-15 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_auto_20181013_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'Liked'), ('d', 'Disliked')], max_length=1, null=True),
        ),
    ]
