# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20181015_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='behavioral_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='medical_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpref',
            name='behavioral_assessment_required',
            field=models.BooleanField(default=False),
        ),
    ]
